  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootcamp-html
  namespace: test
spec:
  selector:
    matchLabels:
      app: bootcamp-html
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: bootcamp-html
    spec:
      containers:
      - name: bootcamp-html
        image: baran6703/baranhub:v$DOCKER_BUILD_NUMBER
        ports:
        - containerPort: 80
